# Configuration for MTR Dipole Test
# Release notes: Initial Release
# Date: 5/16/2025
# Harness P/N: 143230
Name: Dipole Test - MTR
Version: v1.0.1
Date: 5.16.2025
Copyright: Terran Orbital
User_Entry: False                         	# True or False
Log_Title: MTR-111181 Dipole Test Log
Loop_Number: 1
Loop_Delay: 10                            	# sec
Debug: False                              	# True or False
Calculate_Dipole_Target: False            	# True or False
Move_Report_To_N_Drive: False             	# True or False
N_Drive_Report_Path: C:\Module Inventory           # Network report path N:\Module Inventory
Test_Equipment:
  Magnetometer_COM: COM3
  Magnetometer_Baud_Rate: '9600'
  Magnetometer_Write_Delay: '0.5'         	# sec
  Power_Supply_Model_A: 5748A
  Power_Supply_Model_B: 5768A
  Power_Supply_A_Resource_Name: USB0::0x0957::0x9907::US15H9224P::INSTR
  Power_Supply_B_Resource_Name: USB0::0x0957::0xA507::US23J6669R::INSTR
  Power_Supply_Timeout: '2000'              	# ms
  Power_Supply_Voltage_A: :VOLT:LEV 70      	# Voltage 70V
  Power_Supply_Current_Limit_A: ISET 0.068  	# Current Limit 0.066A + 2mA offset
  Power_Supply_Voltage_B: :VOLT:LEV 70      	# Voltage 70V
  Power_Supply_Current_Limit_B: ISET 0.052  	# Current Limit 0.050A + 2mA offset
  DAQ_Model: DAQ970A
  DAQ_Resource_Name: USB0::0x2A8D::0x5101::MY58015854::INSTR
  DAQ_Timeout: '2000'                       	# ms
  DAQ_Digitize_Config_A: ACQ:CURR:DC 0.1,500,0.001,(@121)  # Range:100mA; Count:500; Timer:1ms
  DAQ_Digitize_Config_B: ACQ:CURR:DC 0.1,500,0.001,(@122)  # Range:100mA; Count:500; Timer:1ms
Test_Constant:
  MI: 'xxxx'
  R0_A: '1000'                              	# ohm
  T0_A: '25'                                	# C
  R0_B: '1243'                              	# ohm
  T0_B: '26'                                	# C
  X_DISTANCE_MAGNETOMETER: '1'              	# m
  T_TARGET: '25'                            	# C
  ALPHA: '0.00393'
  L_WINDABLE_LENGTH: '0.28575'              	# Not Used
  CURRENT_AVERAGE_COUNT: '19'
  MAGNET_AVERAGE_COUNT: '10'
  Data_Decimal_Num: 3
  Voltage_Meas_Delay: 5                     	# sec
  Current_Meas_Delay: 5                     	# sec
Test_Limits:
  Dipole_Moment_A_Min: '24'
  Dipole_Moment_B_Min: '20'
  Dipole_Moment_AB_Min: '30'
  Coil_A_Current_Min: '0.063'
  Coil_A_Current_Max: '0.070'
  Coil_B_Current_Min: '0.047'
  Coil_B_Current_Max: '0.053'
  Coil_Voltage_Min: '60'
  Coil_Voltage_Max: '72'

